spring:
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      cache-null-values: false
    type: redis
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    # mysql
#    database: h2
#  sql:
#    init:
#      mode: never
#  datasource:
#      url: jdbc:h2:tcp://localhost/~/redis
#      driver-class-name: org.h2.Driver
#      username: sa

    database: mysql
  sql:
    init:
      mode: never
  datasource:
    url: jdbc:mysql://localhost:3306/redis
    username: root
    password: password1
